package com.capstone.personalityTest.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response DTO received from Python AI service after complete analysis.
 * Contains all AI-generated content including career recommendations, learning paths, and job matches.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CompleteAIResponse {

    /**
     * Personality code that was analyzed (e.g., "R-I-A")
     * Echo back from the request for verification
     */
    private String personalityCode;

    /**
     * AI-generated career recommendations based on personality code
     * Retrieved from RAG system using ChromaDB
     * Contains detailed career guidance in Arabic
     */
    private String careerRecommendations;

    /**
     * Learning path suggestions including universities and courses
     * Generated by learning path agent
     * Contains educational recommendations
     */
    private String learningPath;

    /**
     * Job matching results
     * JSON string containing matched jobs with scores
     * Generated by job matching agent
     */
    private String jobMatches;

    /**
     * Whether the comprehensive email was successfully sent to the student
     * true if email sent successfully, false otherwise
     */
    private boolean emailSent;
}
