package com.capstone.personalityTest.model.testm;

import com.capstone.personalityTest.model.testm.TestAttempt.TestAttempt;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Entity representing AI analysis results for a test attempt.
 * Stores the complete output from Python AI service including:
 * - Career recommendations (from RAG)
 * - Learning path suggestions (from learning agent)
 * - Job matches (from job matching agent)
 * - Email delivery status
 * 
 * This entity has a one-to-one relationship with TestAttempt.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "ai_results")
public class AIResult {

    /**
     * Primary key - auto-generated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * One-to-one relationship with TestAttempt
     * Each test attempt can have only one AI result
     * Unique constraint ensures no duplicate AI results for same attempt
     */
    @OneToOne
    @JoinColumn(name = "test_attempt_id", unique = true)
    private TestAttempt testAttempt;

    /**
     * Personality code analyzed (e.g., "R-I-A")
     * This is the top 3 metrics from the test
     * Cannot be null as it's the basis for all recommendations
     */
    @Column(nullable = false)
    private String personalityCode;

    /**
     * AI-generated career recommendations
     * Retrieved from RAG system (ChromaDB + LLM)
     * Contains detailed career guidance in Arabic
     * Stored as TEXT to handle long content
     */
    @Column(columnDefinition = "TEXT")
    private String careerRecommendations;

    /**
     * Learning path suggestions
     * Generated by learning path agent
     * Includes universities and courses recommendations
     * Stored as TEXT to handle long content
     */
    @Column(columnDefinition = "TEXT")
    private String learningPath;

    /**
     * Job matching results
     * JSON string containing matched jobs with scores
     * Generated by job matching agent
     * Stored as TEXT to handle JSON data
     */
    @Column(columnDefinition = "TEXT")
    private String jobMatches;

    /**
     * Whether the comprehensive email was sent to the student
     * true = email sent successfully
     * false = email failed or not sent
     */
    private boolean emailSent;

    /**
     * Timestamp when AI analysis was completed and saved
     * Used for tracking and auditing
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;
}
